(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-600-1.png':'../images/video-300-1.png');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/pasted-image-466.jpg':'../images/pasted-image-233.jpg');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'../images/video-824.png':'../images/video-412.png');
var e=document.querySelector('.un14');e.setAttribute('src',(dpi>1)?'../images/video-824-1.png':'../images/video-412-1.png');
var e=document.querySelector('.un16');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un17');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un19');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un20');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un22');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un24');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un25');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un26');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un28');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un29');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un30');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un32');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un37');e.setAttribute('src',(dpi>1)?'../images/video-600.png':'../images/video-300.png');
var e=document.querySelector('.un38');e.setAttribute('src',(dpi>1)?'../images/video-600-1.png':'../images/video-300-1.png');
var e=document.querySelector('.un40');e.setAttribute('src',(dpi>1)?'../images/video-600-1.png':'../images/video-300-1.png');
var e=document.querySelector('.un41');e.setAttribute('src',(dpi>1)?'../images/video-600-1.png':'../images/video-300-1.png');
var e=document.querySelector('.un42');e.setAttribute('src',(dpi>1)?'../images/video-600-1.png':'../images/video-300-1.png');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-600.png':'../images/video-300.png');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/pasted-image-374.jpg':'../images/pasted-image-187.jpg');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'../images/video-660.png':'../images/video-330-1.png');
var e=document.querySelector('.un14');e.setAttribute('src',(dpi>1)?'../images/video-660.png':'../images/video-330-1.png');
var e=document.querySelector('.un16');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un17');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un19');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un20');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un22');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un24');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un25');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un26');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un28');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un29');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un30');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un32');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un37');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un38');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un40');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un41');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var e=document.querySelector('.un42');e.setAttribute('src',(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-480.png':'../images/video-240-1.png');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/pasted-image-298.jpg':'../images/pasted-image-149.jpg');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'../images/video-528.png':'../images/video-264.png');
var e=document.querySelector('.un14');e.setAttribute('src',(dpi>1)?'../images/video-528-1.png':'../images/video-264-1.png');
var e=document.querySelector('.un16');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un17');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un19');e.setAttribute('src',(dpi>1)?'../images/video-384-1.png':'../images/video-192-1.png');
var e=document.querySelector('.un20');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un22');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un24');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un25');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un26');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un28');e.setAttribute('src',(dpi>1)?'../images/video-384-1.png':'../images/video-192-1.png');
var e=document.querySelector('.un29');e.setAttribute('src',(dpi>1)?'../images/video-384-1.png':'../images/video-192-1.png');
var e=document.querySelector('.un30');e.setAttribute('src',(dpi>1)?'../images/video-384-1.png':'../images/video-192-1.png');
var e=document.querySelector('.un32');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un37');e.setAttribute('src',(dpi>1)?'../images/video-384.png':'../images/video-192.png');
var e=document.querySelector('.un38');e.setAttribute('src',(dpi>1)?'../images/video-384-2.png':'../images/video-192-2.png');
var e=document.querySelector('.un40');e.setAttribute('src',(dpi>1)?'../images/video-384-2.png':'../images/video-192-2.png');
var e=document.querySelector('.un41');e.setAttribute('src',(dpi>1)?'../images/video-384-2.png':'../images/video-192-2.png');
var e=document.querySelector('.un42');e.setAttribute('src',(dpi>1)?'../images/video-384-2.png':'../images/video-192-2.png');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-384.png':'../images/video-192.png');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/pasted-image-188.jpg':'../images/pasted-image-94.jpg');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'../images/video-330.png':'../images/video-165.png');
var e=document.querySelector('.un14');e.setAttribute('src',(dpi>1)?'../images/video-330.png':'../images/video-165.png');
var e=document.querySelector('.un16');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un17');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un19');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un20');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un22');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un24');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un25');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un26');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un28');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un29');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un30');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un32');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un37');e.setAttribute('src',(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');
var e=document.querySelector('.un38');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un40');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un41');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var e=document.querySelector('.un42');e.setAttribute('src',(dpi>1)?'../images/video-240.png':'../images/video-120.png');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-240-2.png':'../images/video-120-1.png');}else{var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/pasted-image-124.jpg':'../images/pasted-image-62.jpg');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'../images/video-220.png':'../images/video-110.png');
var e=document.querySelector('.un14');e.setAttribute('src',(dpi>1)?'../images/video-220.png':'../images/video-110.png');
var e=document.querySelector('.un16');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un17');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un19');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un20');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un22');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un24');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un25');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un26');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un28');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un29');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un30');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un32');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un37');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un38');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un40');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un41');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var e=document.querySelector('.un42');e.setAttribute('src',(dpi>1)?'../images/video-160.png':'../images/video-80.png');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'../images/video-160.png':'../images/video-80.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
wl=new woolite();
wl.init();
wl.addAnimation($('.un1'), "1.00s", "2.00s", 1, 100);
wl.addAnimation($('.un2'), "1.00s", "3.10s", 1, 100);
wl.addAnimation($('.un3'), "1.00s", "5.00s", 1, 100);
wl.addAnimation($('.un4'), "1.00s", "6.00s", 1, 100);
wl.addAnimation($('.un5'), "1.00s", "7.00s", 1, 100);
wl.addAnimation($('.un6'), "1.00s", "8.00s", 1, 100);
wl.addAnimation($('.un7'), "1.00s", "9.00s", 1, 100);
wl.addAnimation($('.un8'), "1.00s", "10.00s", 1, 100);
wl.addAnimation($('.un9'), "1.00s", "11.00s", 1, 100);
wl.addAnimation($('.un10'), "1.00s", "12.00s", 1, 100);
wl.addAnimation($('.un11'), "1.00s", "12.00s", 1, 100);
wl.addAnimation($('.un12'), "1.00s", "12.00s", 1, 100);
wl.addAnimation($('.un15'), "1.00s", "5.00s", 1, 100);
wl.addAnimation($('.un18'), "1.00s", "6.00s", 1, 100);
wl.addAnimation($('.un23'), "1.00s", "7.00s", 1, 100);
wl.addAnimation($('.un27'), "1.00s", "8.00s", 1, 100);
wl.addAnimation($('.un31'), "1.00s", "9.00s", 1, 100);
wl.addAnimation($('.un35'), "1.00s", "10.00s", 1, 100);
wl.addAnimation($('.un39'), "1.00s", "11.00s", 1, 100);
wl.addAnimation($('.un43'), "1.00s", "12.00s", 1, 100);
wl.start();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un236 source');ldsrcset('.un237 source');ldsrcset('.un238 source');ldsrcset('.un239 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}